---
- name: generate proxy/auth systemd service
  template:
    src: teleport.service.j2
    dest: /etc/systemd/system/teleport.service

- name: generate teleport.yaml config file
  template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml

- name: start the teleport service
  systemd:
    name: teleport
    daemon_reload: true
    state: started
    enabled: true
